version: "3"
services:
  db:
    container_name: backend-base-postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend-base
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    container_name: backend-base-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
  minio:
    driver: local
